# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Maven release
      run: mvn release:prepare release:perform -B -s $GITHUB_WORKSPACE/settings.xml --file pom.xml \ 
      -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \ 
      -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} \
      -DautoVersionSubmodules=true \
      -Dtag=${{ github.event.inputs.releaseVersion }}
      env:
        GITHUB_TOKEN: ${{ github.token }}